name: app_aloo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.4.1
  get: ^4.6.6
  flare_flutter: ^3.0.2
  flutter_keyboard_visibility: ^5.4.0
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  package_info_plus: ^3.0.2
  rxdart: ^0.27.7
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.1.11
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
